[package]
name = "redpanda-rust-testing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kafka = "0.9.0"
env_logger = "0.9.0"
openssl = { version = "0.10.40", features = ["vendored"] }
